// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResearchDiscovery.Infrastructure.Persistence;

#nullable disable

namespace ResearchDiscovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710031914_AddSignalsAndInterleaving")]
    partial class AddSignalsAndInterleaving
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CompositeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompositeScore");

                    b.HasIndex("PaperId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Bookmark", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaperId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.CategoryIngestionState", b =>
                {
                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HighWaterMarkUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCompletedRunUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryIngestionStates");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.IngestionLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AcquiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Holder")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("Stamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("IngestionLocks");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("PapersAdded")
                        .HasColumnType("integer");

                    b.Property<int>("PapersFetched")
                        .HasColumnType("integer");

                    b.Property<int>("PapersUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.InteractionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<long?>("SearchEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("PaperId");

                    b.ToTable("InteractionEvents");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.LlmStepConfig", b =>
                {
                    b.Property<string>("Step")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Step");

                    b.ToTable("LlmStepConfigs");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Paper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AbsUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArxivId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("FirstIngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LatestVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("PrimaryCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArxivId")
                        .IsUnique();

                    b.HasIndex("PrimaryCategoryId");

                    b.HasIndex("PublishedUtc", "Id")
                        .IsDescending();

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperCategory", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("PaperId", "CategoryId");

                    b.HasIndex("CategoryId", "PaperId");

                    b.ToTable("PaperCategories");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperEmbedding", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("PaperId");

                    b.ToTable("PaperEmbeddings");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperSignal", b =>
                {
                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CitationCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GitHubStars")
                        .HasColumnType("integer");

                    b.Property<int?>("InfluentialCitationCount")
                        .HasColumnType("integer");

                    b.HasKey("PaperId");

                    b.ToTable("PaperSignals");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.SearchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueryText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ResultLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCandidates")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("SearchEvents");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.SearchEventResult", b =>
                {
                    b.Property<long>("SearchEventId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWildcard")
                        .HasColumnType("boolean");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<string>("Proximity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Variant")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("SearchEventId", "Rank");

                    b.HasIndex("PaperId");

                    b.ToTable("SearchEventResults");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("ResearchDiscovery.Domain.Entities.AnalysisResult", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithOne("Bookmark")
                        .HasForeignKey("ResearchDiscovery.Domain.Entities.Bookmark", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.CategoryIngestionState", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Category", "Category")
                        .WithOne()
                        .HasForeignKey("ResearchDiscovery.Domain.Entities.CategoryIngestionState", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.InteractionEvent", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Paper", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Category", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryCategory");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperCategory", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Category", "Category")
                        .WithMany("PaperCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithMany("PaperCategories")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperEmbedding", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithOne("Embedding")
                        .HasForeignKey("ResearchDiscovery.Domain.Entities.PaperEmbedding", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.PaperSignal", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithOne("Signal")
                        .HasForeignKey("ResearchDiscovery.Domain.Entities.PaperSignal", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.SearchEventResult", b =>
                {
                    b.HasOne("ResearchDiscovery.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchDiscovery.Domain.Entities.SearchEvent", "SearchEvent")
                        .WithMany("Results")
                        .HasForeignKey("SearchEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("SearchEvent");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Category", b =>
                {
                    b.Navigation("PaperCategories");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.Paper", b =>
                {
                    b.Navigation("AnalysisResult");

                    b.Navigation("Bookmark");

                    b.Navigation("Embedding");

                    b.Navigation("PaperCategories");

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("ResearchDiscovery.Domain.Entities.SearchEvent", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
